project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "imgs/**"
    - "libs/**"

website:
  title: "AI Lectures"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: classification-basics-1d.qmd
        text: "Lec 1"
      - href: classification-2d-boundaries.qmd
        text: "Lec 2"
      - href: classification-evaluation.qmd
        text: "Lec 3"
      - href: clustering-kmeans.qmd
        text: "Lec 4"
      - href: dimensionality-pca.qmd
        text: "Lec 5"
