name: ai
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - jupyter
  - nbformat
  - nbclient
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - altair
  - vl-convert-python
  - pip
  - pip:
      - japanize-matplotlib
